export const workers = [
  {
    id: 1,
    name: "Budi Santoso",
    role: "Senior Process Engineer",
    years: 15,
    crew: "A",
    bio: "A pillar of the SRU team for over 15 years, Budi specializes in Claus process optimization and catalyst lifecycle management. He has led three major turnaround projects and mentored dozens of young engineers at Cilacap Refinery.",
    photo: null,
  },
  {
    id: 2,
    name: "Dewi Rahayu",
    role: "Control Room Operator",
    years: 9,
    crew: "B",
    bio: "Dewi is one of the most skilled DCS operators in the unit, known for her calm and precise response during process upsets. She has been instrumental in training new operators on the SCADA interface and emergency shutdown procedures.",
    photo: null,
  },
  {
    id: 3,
    name: "Ahmad Fauzi",
    role: "Instrument & Electrical Technician",
    years: 12,
    crew: "C",
    bio: "Ahmad maintains the critical instrumentation and electrical systems that keep the SRU running. His expertise covers flow transmitters, analyzers, and the safety instrumented system (SIS) for the tail gas unit.",
    photo: null,
  },
  {
    id: 4,
    name: "Rizky Pratama",
    role: "Process Operator",
    years: 6,
    crew: "D",
    bio: "Rizky joined the SRU team fresh from vocational training and quickly stood out for his diligence and sharp observational skills. He monitors field equipment across all three converter stages and is a key part of the night shift response team.",
    photo: null,
  },
  {
    id: 5,
    name: "Siti Nurhaliza",
    role: "HSE Officer",
    years: 8,
    crew: "A",
    bio: "Siti ensures every shift operates under the strictest health, safety, and environmental standards. She has developed the SRU's H₂S gas detection audit protocol and leads quarterly emergency evacuation drills across the unit.",
    photo: null,
  },
  {
    id: 6,
    name: "Hendra Wijaya",
    role: "Maintenance Supervisor",
    years: 18,
    crew: "B",
    bio: "With nearly two decades at Cilacap Refinery, Hendra oversees all rotating and static equipment maintenance schedules. His leadership during the 2023 Claus reactor refractory repair is regarded as a benchmark for future turnarounds.",
    photo: null,
  },
  {
    id: 7,
    name: "Yusuf Hakim",
    role: "Shift Supervisor",
    years: 11,
    crew: "C",
    bio: "Yusuf coordinates all on-shift activities, ensuring seamless communication between field operators, the control room, and engineering support. He is known for his methodical handover briefings and his commitment to zero-incident operations.",
    photo: null,
  },
]
